/********************************************************************************
** Form generated from reading UI file 'scoreboardmain.ui'
**
** Created by: Qt User Interface Compiler version 5.12.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SCOREBOARDMAIN_H
#define UI_SCOREBOARDMAIN_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ScoreboardMain
{
public:
    QAction *About_ActionBar;
    QAction *Hotkey_ActionBar;
    QAction *ChangeLog_ActionBar;
    QAction *actionXxRocketshotxX;
    QAction *actionSickmind33;
    QAction *actionDonate;
    QWidget *centralWidget;
    QTabWidget *Remote;
    QWidget *tab;
    QPushButton *AwayUp2_Button;
    QPushButton *PeriodUP_Button;
    QLabel *AwayScore_Label;
    QSpinBox *Seconds_Input;
    QPushButton *Update_Team_Button;
    QPushButton *AwayUP_Button;
    QPushButton *HomeUP_Button;
    QPushButton *HomeUP2_Button;
    QPushButton *AwayDOWN_Button;
    QPushButton *PeriodDOWN_Button;
    QLabel *Timeset_Label;
    QLabel *HomeScore_Label;
    QPushButton *Reset_Button;
    QPushButton *Start_Button;
    QLabel *Period_Label;
    QPushButton *HomeDOWN_Button;
    QSpinBox *Minutes_Input;
    QPushButton *Swap_Button;
    QPushButton *Reset_Score_Button;
    QLabel *Clock_Symble_Label;
    QComboBox *Home_Option;
    QComboBox *Away_Option;
    QRadioButton *TwentyP_Radio;
    QRadioButton *TenP_Radio;
    QRadioButton *FiveP_Radio;
    QRadioButton *FifteenP_Radio;
    QLabel *Clock_Minute10;
    QLabel *Clock_Minute1;
    QLabel *Clock_Second10;
    QLabel *Clock_Second1;
    QLabel *Clock_Colon;
    QPushButton *Minute10up;
    QPushButton *Minute1up;
    QPushButton *Second10up;
    QPushButton *Second1up;
    QPushButton *Minute10down;
    QPushButton *Minute1down;
    QPushButton *Second10down;
    QPushButton *Second1down;
    QPushButton *MS10up;
    QPushButton *MS10down;
    QLabel *Clock_Colon_2;
    QLabel *Clock_MS10;
    QPushButton *Update_Timer;
    QPushButton *Intermission_Button;
    QLabel *home_label;
    QLabel *away_label;
    QComboBox *Home_Player;
    QLabel *home_player_label;
    QSpinBox *AP1M;
    QLabel *Clock_Symble_Label_3;
    QSpinBox *AP1S;
    QSpinBox *AP2M;
    QLabel *Clock_Symble_Label_4;
    QSpinBox *AP2S;
    QSpinBox *HP1M;
    QLabel *Clock_Symble_Label_5;
    QSpinBox *HP1S;
    QSpinBox *HP2M;
    QLabel *Clock_Symble_Label_6;
    QSpinBox *HP2S;
    QCheckBox *HP1;
    QCheckBox *HP2;
    QCheckBox *AP1;
    QCheckBox *AP2;
    QLabel *home_pen_label;
    QLabel *away_pen_label;
    QPushButton *Update_Pens;
    QPushButton *End_Game_Button;
    QPushButton *Reset_All;
    QCheckBox *show_score;
    QComboBox *comboTheme;
    QWidget *S;
    QWidget *verticalLayoutWidget_4;
    QVBoxLayout *verticalLayout_4;
    QCheckBox *Hotkey_Checkbox;
    QPushButton *Usehotkey_Help;
    QWidget *verticalLayoutWidget_5;
    QVBoxLayout *verticalLayout_5;
    QFrame *line_5;
    QCheckBox *Countdown_Checkbox;
    QLabel *Countdown_Detail;
    QWidget *verticalLayoutWidget_6;
    QVBoxLayout *verticalLayout_6;
    QCheckBox *Alway_on_top_Checkbox;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_3;
    QFrame *line_6;
    QFrame *line_7;
    QFrame *line_8;
    QFrame *line_9;
    QPushButton *SpeedHelp_Button;
    QCheckBox *TimerPreset_Checkbox;
    QCheckBox *checkBox;
    QFrame *line_10;
    QCheckBox *CurrentTime_Checkbox;
    QCheckBox *Stopwatch_Checkbox;
    QLabel *label_2;
    QLineEdit *AwayName_Input;
    QLineEdit *HomeName_Input;
    QPushButton *StopMusic_Button;
    QCheckBox *To_Checkbox;
    QSpinBox *Seconds_To_Input;
    QLabel *Clock_Symble_Label_2;
    QSpinBox *Minutes_To_In;
    QWidget *Sound;
    QCheckBox *PlaySound_Checkbox;
    QLineEdit *BrowseFile_Input;
    QPushButton *Browsefile_Button;
    QSlider *horizontalSlider;
    QLabel *label;
    QPushButton *TestSound_Button;
    QLabel *Warning_Label;
    QSlider *SoundSpeed_Slider;
    QLabel *thumb;
    QWidget *Remote1;
    QLabel *Status;
    QPushButton *pushButton;
    QFrame *line_4;
    QLabel *IP_Label;
    QLabel *IP_Label_2;
    QLabel *Testing;
    QMenuBar *menuBar;
    QMenu *menuAbout;
    QMenu *menuContributers;
    QMenu *menuDonate;

    void setupUi(QMainWindow *ScoreboardMain)
    {
        if (ScoreboardMain->objectName().isEmpty())
            ScoreboardMain->setObjectName(QString::fromUtf8("ScoreboardMain"));
        ScoreboardMain->setWindowModality(Qt::ApplicationModal);
        ScoreboardMain->resize(581, 875);
        ScoreboardMain->setStyleSheet(QString::fromUtf8("alternate-background-color: rgb(253, 253, 253);"));
        About_ActionBar = new QAction(ScoreboardMain);
        About_ActionBar->setObjectName(QString::fromUtf8("About_ActionBar"));
        About_ActionBar->setEnabled(true);
        Hotkey_ActionBar = new QAction(ScoreboardMain);
        Hotkey_ActionBar->setObjectName(QString::fromUtf8("Hotkey_ActionBar"));
        ChangeLog_ActionBar = new QAction(ScoreboardMain);
        ChangeLog_ActionBar->setObjectName(QString::fromUtf8("ChangeLog_ActionBar"));
        actionXxRocketshotxX = new QAction(ScoreboardMain);
        actionXxRocketshotxX->setObjectName(QString::fromUtf8("actionXxRocketshotxX"));
        actionSickmind33 = new QAction(ScoreboardMain);
        actionSickmind33->setObjectName(QString::fromUtf8("actionSickmind33"));
        actionDonate = new QAction(ScoreboardMain);
        actionDonate->setObjectName(QString::fromUtf8("actionDonate"));
        QFont font;
        font.setPointSize(8);
        actionDonate->setFont(font);
        centralWidget = new QWidget(ScoreboardMain);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        centralWidget->setStyleSheet(QString::fromUtf8(""));
        Remote = new QTabWidget(centralWidget);
        Remote->setObjectName(QString::fromUtf8("Remote"));
        Remote->setEnabled(true);
        Remote->setGeometry(QRect(0, 0, 1201, 811));
        Remote->setFocusPolicy(Qt::StrongFocus);
        Remote->setLayoutDirection(Qt::LeftToRight);
        Remote->setStyleSheet(QString::fromUtf8(""));
        Remote->setTabPosition(QTabWidget::North);
        Remote->setTabShape(QTabWidget::Rounded);
        Remote->setDocumentMode(false);
        Remote->setTabsClosable(false);
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        tab->setStyleSheet(QString::fromUtf8(""));
        AwayUp2_Button = new QPushButton(tab);
        AwayUp2_Button->setObjectName(QString::fromUtf8("AwayUp2_Button"));
        AwayUp2_Button->setGeometry(QRect(440, 140, 71, 31));
        QFont font1;
        font1.setPointSize(11);
        AwayUp2_Button->setFont(font1);
        AwayUp2_Button->setFocusPolicy(Qt::NoFocus);
        PeriodUP_Button = new QPushButton(tab);
        PeriodUP_Button->setObjectName(QString::fromUtf8("PeriodUP_Button"));
        PeriodUP_Button->setGeometry(QRect(250, 350, 61, 51));
        PeriodUP_Button->setFocusPolicy(Qt::NoFocus);
        AwayScore_Label = new QLabel(tab);
        AwayScore_Label->setObjectName(QString::fromUtf8("AwayScore_Label"));
        AwayScore_Label->setGeometry(QRect(440, 210, 71, 71));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Arial"));
        font2.setPointSize(48);
        AwayScore_Label->setFont(font2);
        AwayScore_Label->setAlignment(Qt::AlignCenter);
        Seconds_Input = new QSpinBox(tab);
        Seconds_Input->setObjectName(QString::fromUtf8("Seconds_Input"));
        Seconds_Input->setGeometry(QRect(330, 300, 42, 22));
        Seconds_Input->setMaximum(59);
        Update_Team_Button = new QPushButton(tab);
        Update_Team_Button->setObjectName(QString::fromUtf8("Update_Team_Button"));
        Update_Team_Button->setGeometry(QRect(10, 500, 111, 51));
        QFont font3;
        font3.setPointSize(10);
        Update_Team_Button->setFont(font3);
        Update_Team_Button->setFocusPolicy(Qt::NoFocus);
        Update_Team_Button->setStyleSheet(QString::fromUtf8("alternate-background-color: rgb(85, 170, 127);"));
        AwayUP_Button = new QPushButton(tab);
        AwayUP_Button->setObjectName(QString::fromUtf8("AwayUP_Button"));
        AwayUP_Button->setGeometry(QRect(440, 170, 71, 31));
        QFont font4;
        font4.setPointSize(26);
        AwayUP_Button->setFont(font4);
        AwayUP_Button->setFocusPolicy(Qt::NoFocus);
        HomeUP_Button = new QPushButton(tab);
        HomeUP_Button->setObjectName(QString::fromUtf8("HomeUP_Button"));
        HomeUP_Button->setGeometry(QRect(50, 170, 71, 31));
        HomeUP_Button->setFont(font4);
        HomeUP_Button->setFocusPolicy(Qt::NoFocus);
        HomeUP2_Button = new QPushButton(tab);
        HomeUP2_Button->setObjectName(QString::fromUtf8("HomeUP2_Button"));
        HomeUP2_Button->setGeometry(QRect(50, 140, 71, 31));
        HomeUP2_Button->setFont(font1);
        HomeUP2_Button->setFocusPolicy(Qt::NoFocus);
        AwayDOWN_Button = new QPushButton(tab);
        AwayDOWN_Button->setObjectName(QString::fromUtf8("AwayDOWN_Button"));
        AwayDOWN_Button->setGeometry(QRect(440, 290, 71, 31));
        AwayDOWN_Button->setFont(font4);
        AwayDOWN_Button->setFocusPolicy(Qt::NoFocus);
        PeriodDOWN_Button = new QPushButton(tab);
        PeriodDOWN_Button->setObjectName(QString::fromUtf8("PeriodDOWN_Button"));
        PeriodDOWN_Button->setGeometry(QRect(250, 470, 61, 51));
        PeriodDOWN_Button->setFocusPolicy(Qt::NoFocus);
        Timeset_Label = new QLabel(tab);
        Timeset_Label->setObjectName(QString::fromUtf8("Timeset_Label"));
        Timeset_Label->setGeometry(QRect(180, 300, 61, 21));
        QFont font5;
        font5.setFamily(QString::fromUtf8("Arial"));
        Timeset_Label->setFont(font5);
        HomeScore_Label = new QLabel(tab);
        HomeScore_Label->setObjectName(QString::fromUtf8("HomeScore_Label"));
        HomeScore_Label->setGeometry(QRect(50, 210, 71, 71));
        HomeScore_Label->setFont(font2);
        HomeScore_Label->setAlignment(Qt::AlignCenter);
        Reset_Button = new QPushButton(tab);
        Reset_Button->setObjectName(QString::fromUtf8("Reset_Button"));
        Reset_Button->setGeometry(QRect(130, 500, 111, 51));
        Reset_Button->setFont(font3);
        Reset_Button->setFocusPolicy(Qt::NoFocus);
        Start_Button = new QPushButton(tab);
        Start_Button->setObjectName(QString::fromUtf8("Start_Button"));
        Start_Button->setGeometry(QRect(140, 10, 281, 71));
        QFont font6;
        font6.setFamily(QString::fromUtf8("Microsoft JhengHei UI"));
        font6.setPointSize(20);
        font6.setBold(false);
        font6.setWeight(50);
        Start_Button->setFont(font6);
        Start_Button->setFocusPolicy(Qt::NoFocus);
        Start_Button->setStyleSheet(QString::fromUtf8("background: green"));
        Period_Label = new QLabel(tab);
        Period_Label->setObjectName(QString::fromUtf8("Period_Label"));
        Period_Label->setGeometry(QRect(250, 400, 61, 71));
        Period_Label->setFont(font2);
        Period_Label->setAlignment(Qt::AlignCenter);
        HomeDOWN_Button = new QPushButton(tab);
        HomeDOWN_Button->setObjectName(QString::fromUtf8("HomeDOWN_Button"));
        HomeDOWN_Button->setGeometry(QRect(50, 290, 71, 31));
        HomeDOWN_Button->setFont(font4);
        HomeDOWN_Button->setFocusPolicy(Qt::NoFocus);
        Minutes_Input = new QSpinBox(tab);
        Minutes_Input->setObjectName(QString::fromUtf8("Minutes_Input"));
        Minutes_Input->setGeometry(QRect(260, 300, 42, 22));
        Swap_Button = new QPushButton(tab);
        Swap_Button->setObjectName(QString::fromUtf8("Swap_Button"));
        Swap_Button->setGeometry(QRect(440, 440, 111, 51));
        Swap_Button->setFont(font3);
        Swap_Button->setFocusPolicy(Qt::NoFocus);
        Reset_Score_Button = new QPushButton(tab);
        Reset_Score_Button->setObjectName(QString::fromUtf8("Reset_Score_Button"));
        Reset_Score_Button->setGeometry(QRect(440, 500, 111, 51));
        Reset_Score_Button->setFont(font3);
        Reset_Score_Button->setFocusPolicy(Qt::NoFocus);
        Reset_Score_Button->setStyleSheet(QString::fromUtf8(""));
        Clock_Symble_Label = new QLabel(tab);
        Clock_Symble_Label->setObjectName(QString::fromUtf8("Clock_Symble_Label"));
        Clock_Symble_Label->setGeometry(QRect(310, 300, 20, 21));
        QFont font7;
        font7.setFamily(QString::fromUtf8("Arial"));
        font7.setPointSize(18);
        font7.setBold(true);
        font7.setWeight(75);
        Clock_Symble_Label->setFont(font7);
        Home_Option = new QComboBox(tab);
        Home_Option->setObjectName(QString::fromUtf8("Home_Option"));
        Home_Option->setGeometry(QRect(10, 90, 261, 33));
        QFont font8;
        font8.setPointSize(14);
        font8.setBold(true);
        font8.setWeight(75);
        Home_Option->setFont(font8);
        Home_Option->setFocusPolicy(Qt::ClickFocus);
        Home_Option->setEditable(true);
        Away_Option = new QComboBox(tab);
        Away_Option->setObjectName(QString::fromUtf8("Away_Option"));
        Away_Option->setGeometry(QRect(290, 90, 261, 33));
        Away_Option->setFont(font8);
        Away_Option->setFocusPolicy(Qt::ClickFocus);
        Away_Option->setEditable(true);
        TwentyP_Radio = new QRadioButton(tab);
        TwentyP_Radio->setObjectName(QString::fromUtf8("TwentyP_Radio"));
        TwentyP_Radio->setGeometry(QRect(380, 600, 82, 17));
        TwentyP_Radio->setChecked(true);
        TenP_Radio = new QRadioButton(tab);
        TenP_Radio->setObjectName(QString::fromUtf8("TenP_Radio"));
        TenP_Radio->setGeometry(QRect(200, 600, 82, 17));
        FiveP_Radio = new QRadioButton(tab);
        FiveP_Radio->setObjectName(QString::fromUtf8("FiveP_Radio"));
        FiveP_Radio->setGeometry(QRect(110, 600, 82, 17));
        FifteenP_Radio = new QRadioButton(tab);
        FifteenP_Radio->setObjectName(QString::fromUtf8("FifteenP_Radio"));
        FifteenP_Radio->setGeometry(QRect(290, 600, 82, 17));
        Clock_Minute10 = new QLabel(tab);
        Clock_Minute10->setObjectName(QString::fromUtf8("Clock_Minute10"));
        Clock_Minute10->setGeometry(QRect(160, 190, 41, 61));
        QFont font9;
        font9.setFamily(QString::fromUtf8("Arial"));
        font9.setPointSize(55);
        font9.setBold(false);
        font9.setWeight(50);
        Clock_Minute10->setFont(font9);
        Clock_Minute10->setAlignment(Qt::AlignCenter);
        Clock_Minute1 = new QLabel(tab);
        Clock_Minute1->setObjectName(QString::fromUtf8("Clock_Minute1"));
        Clock_Minute1->setGeometry(QRect(200, 190, 41, 61));
        Clock_Minute1->setFont(font9);
        Clock_Minute1->setAlignment(Qt::AlignCenter);
        Clock_Second10 = new QLabel(tab);
        Clock_Second10->setObjectName(QString::fromUtf8("Clock_Second10"));
        Clock_Second10->setGeometry(QRect(260, 190, 41, 61));
        Clock_Second10->setFont(font9);
        Clock_Second10->setAlignment(Qt::AlignCenter);
        Clock_Second1 = new QLabel(tab);
        Clock_Second1->setObjectName(QString::fromUtf8("Clock_Second1"));
        Clock_Second1->setGeometry(QRect(300, 190, 41, 61));
        Clock_Second1->setFont(font9);
        Clock_Second1->setAlignment(Qt::AlignCenter);
        Clock_Colon = new QLabel(tab);
        Clock_Colon->setObjectName(QString::fromUtf8("Clock_Colon"));
        Clock_Colon->setGeometry(QRect(240, 190, 21, 61));
        Clock_Colon->setFont(font9);
        Clock_Colon->setAlignment(Qt::AlignCenter);
        Minute10up = new QPushButton(tab);
        Minute10up->setObjectName(QString::fromUtf8("Minute10up"));
        Minute10up->setGeometry(QRect(160, 150, 41, 31));
        Minute10up->setFont(font4);
        Minute10up->setFocusPolicy(Qt::NoFocus);
        Minute1up = new QPushButton(tab);
        Minute1up->setObjectName(QString::fromUtf8("Minute1up"));
        Minute1up->setGeometry(QRect(200, 150, 41, 31));
        Minute1up->setFont(font4);
        Minute1up->setFocusPolicy(Qt::NoFocus);
        Second10up = new QPushButton(tab);
        Second10up->setObjectName(QString::fromUtf8("Second10up"));
        Second10up->setGeometry(QRect(260, 150, 41, 31));
        Second10up->setFont(font4);
        Second10up->setFocusPolicy(Qt::NoFocus);
        Second1up = new QPushButton(tab);
        Second1up->setObjectName(QString::fromUtf8("Second1up"));
        Second1up->setGeometry(QRect(300, 150, 41, 31));
        Second1up->setFont(font4);
        Second1up->setFocusPolicy(Qt::NoFocus);
        Minute10down = new QPushButton(tab);
        Minute10down->setObjectName(QString::fromUtf8("Minute10down"));
        Minute10down->setGeometry(QRect(160, 260, 41, 31));
        Minute10down->setFont(font4);
        Minute10down->setFocusPolicy(Qt::NoFocus);
        Minute1down = new QPushButton(tab);
        Minute1down->setObjectName(QString::fromUtf8("Minute1down"));
        Minute1down->setGeometry(QRect(200, 260, 41, 31));
        Minute1down->setFont(font4);
        Minute1down->setFocusPolicy(Qt::NoFocus);
        Second10down = new QPushButton(tab);
        Second10down->setObjectName(QString::fromUtf8("Second10down"));
        Second10down->setGeometry(QRect(260, 260, 41, 31));
        Second10down->setFont(font4);
        Second10down->setFocusPolicy(Qt::NoFocus);
        Second1down = new QPushButton(tab);
        Second1down->setObjectName(QString::fromUtf8("Second1down"));
        Second1down->setGeometry(QRect(300, 260, 41, 31));
        Second1down->setFont(font4);
        Second1down->setFocusPolicy(Qt::NoFocus);
        MS10up = new QPushButton(tab);
        MS10up->setObjectName(QString::fromUtf8("MS10up"));
        MS10up->setGeometry(QRect(360, 150, 41, 31));
        MS10up->setFont(font4);
        MS10up->setFocusPolicy(Qt::NoFocus);
        MS10down = new QPushButton(tab);
        MS10down->setObjectName(QString::fromUtf8("MS10down"));
        MS10down->setGeometry(QRect(360, 260, 41, 31));
        MS10down->setFont(font4);
        MS10down->setFocusPolicy(Qt::NoFocus);
        Clock_Colon_2 = new QLabel(tab);
        Clock_Colon_2->setObjectName(QString::fromUtf8("Clock_Colon_2"));
        Clock_Colon_2->setGeometry(QRect(340, 190, 21, 61));
        Clock_Colon_2->setFont(font9);
        Clock_Colon_2->setAlignment(Qt::AlignCenter);
        Clock_MS10 = new QLabel(tab);
        Clock_MS10->setObjectName(QString::fromUtf8("Clock_MS10"));
        Clock_MS10->setGeometry(QRect(360, 190, 41, 61));
        Clock_MS10->setFont(font9);
        Clock_MS10->setAlignment(Qt::AlignCenter);
        Update_Timer = new QPushButton(tab);
        Update_Timer->setObjectName(QString::fromUtf8("Update_Timer"));
        Update_Timer->setGeometry(QRect(320, 500, 111, 51));
        Update_Timer->setFont(font3);
        Update_Timer->setFocusPolicy(Qt::NoFocus);
        Intermission_Button = new QPushButton(tab);
        Intermission_Button->setObjectName(QString::fromUtf8("Intermission_Button"));
        Intermission_Button->setGeometry(QRect(130, 440, 111, 51));
        Intermission_Button->setFont(font3);
        Intermission_Button->setFocusPolicy(Qt::NoFocus);
        home_label = new QLabel(tab);
        home_label->setObjectName(QString::fromUtf8("home_label"));
        home_label->setGeometry(QRect(10, 8, 121, 71));
        QFont font10;
        font10.setPointSize(28);
        font10.setBold(true);
        font10.setWeight(75);
        home_label->setFont(font10);
        home_label->setAlignment(Qt::AlignCenter);
        away_label = new QLabel(tab);
        away_label->setObjectName(QString::fromUtf8("away_label"));
        away_label->setGeometry(QRect(430, 10, 121, 71));
        away_label->setFont(font10);
        away_label->setAlignment(Qt::AlignCenter);
        Home_Player = new QComboBox(tab);
        Home_Player->setObjectName(QString::fromUtf8("Home_Player"));
        Home_Player->setGeometry(QRect(600, 90, 411, 33));
        Home_Player->setFont(font8);
        Home_Player->setFocusPolicy(Qt::ClickFocus);
        Home_Player->setEditable(true);
        home_player_label = new QLabel(tab);
        home_player_label->setObjectName(QString::fromUtf8("home_player_label"));
        home_player_label->setGeometry(QRect(600, 10, 181, 71));
        home_player_label->setFont(font10);
        home_player_label->setAlignment(Qt::AlignCenter);
        AP1M = new QSpinBox(tab);
        AP1M->setObjectName(QString::fromUtf8("AP1M"));
        AP1M->setGeometry(QRect(450, 370, 42, 22));
        AP1M->setValue(2);
        Clock_Symble_Label_3 = new QLabel(tab);
        Clock_Symble_Label_3->setObjectName(QString::fromUtf8("Clock_Symble_Label_3"));
        Clock_Symble_Label_3->setGeometry(QRect(490, 370, 16, 21));
        Clock_Symble_Label_3->setFont(font7);
        AP1S = new QSpinBox(tab);
        AP1S->setObjectName(QString::fromUtf8("AP1S"));
        AP1S->setGeometry(QRect(500, 370, 42, 22));
        AP1S->setMaximum(59);
        AP2M = new QSpinBox(tab);
        AP2M->setObjectName(QString::fromUtf8("AP2M"));
        AP2M->setGeometry(QRect(450, 400, 42, 22));
        AP2M->setValue(2);
        Clock_Symble_Label_4 = new QLabel(tab);
        Clock_Symble_Label_4->setObjectName(QString::fromUtf8("Clock_Symble_Label_4"));
        Clock_Symble_Label_4->setGeometry(QRect(490, 400, 16, 21));
        Clock_Symble_Label_4->setFont(font7);
        AP2S = new QSpinBox(tab);
        AP2S->setObjectName(QString::fromUtf8("AP2S"));
        AP2S->setGeometry(QRect(500, 400, 42, 22));
        AP2S->setMaximum(59);
        HP1M = new QSpinBox(tab);
        HP1M->setObjectName(QString::fromUtf8("HP1M"));
        HP1M->setGeometry(QRect(50, 370, 42, 22));
        HP1M->setValue(2);
        Clock_Symble_Label_5 = new QLabel(tab);
        Clock_Symble_Label_5->setObjectName(QString::fromUtf8("Clock_Symble_Label_5"));
        Clock_Symble_Label_5->setGeometry(QRect(90, 370, 16, 21));
        Clock_Symble_Label_5->setFont(font7);
        HP1S = new QSpinBox(tab);
        HP1S->setObjectName(QString::fromUtf8("HP1S"));
        HP1S->setGeometry(QRect(100, 370, 42, 22));
        HP1S->setMaximum(59);
        HP2M = new QSpinBox(tab);
        HP2M->setObjectName(QString::fromUtf8("HP2M"));
        HP2M->setGeometry(QRect(50, 400, 42, 22));
        HP2M->setValue(2);
        Clock_Symble_Label_6 = new QLabel(tab);
        Clock_Symble_Label_6->setObjectName(QString::fromUtf8("Clock_Symble_Label_6"));
        Clock_Symble_Label_6->setGeometry(QRect(90, 400, 16, 21));
        Clock_Symble_Label_6->setFont(font7);
        HP2S = new QSpinBox(tab);
        HP2S->setObjectName(QString::fromUtf8("HP2S"));
        HP2S->setGeometry(QRect(100, 400, 42, 22));
        HP2S->setMaximum(59);
        HP1 = new QCheckBox(tab);
        HP1->setObjectName(QString::fromUtf8("HP1"));
        HP1->setGeometry(QRect(20, 370, 21, 20));
        HP2 = new QCheckBox(tab);
        HP2->setObjectName(QString::fromUtf8("HP2"));
        HP2->setEnabled(true);
        HP2->setGeometry(QRect(20, 400, 21, 20));
        HP2->setChecked(false);
        AP1 = new QCheckBox(tab);
        AP1->setObjectName(QString::fromUtf8("AP1"));
        AP1->setGeometry(QRect(420, 370, 21, 20));
        AP2 = new QCheckBox(tab);
        AP2->setObjectName(QString::fromUtf8("AP2"));
        AP2->setGeometry(QRect(420, 400, 21, 20));
        home_pen_label = new QLabel(tab);
        home_pen_label->setObjectName(QString::fromUtf8("home_pen_label"));
        home_pen_label->setGeometry(QRect(10, 330, 201, 31));
        QFont font11;
        font11.setPointSize(18);
        font11.setBold(true);
        font11.setWeight(75);
        home_pen_label->setFont(font11);
        home_pen_label->setAlignment(Qt::AlignCenter);
        away_pen_label = new QLabel(tab);
        away_pen_label->setObjectName(QString::fromUtf8("away_pen_label"));
        away_pen_label->setGeometry(QRect(350, 330, 201, 31));
        away_pen_label->setFont(font11);
        away_pen_label->setAlignment(Qt::AlignCenter);
        Update_Pens = new QPushButton(tab);
        Update_Pens->setObjectName(QString::fromUtf8("Update_Pens"));
        Update_Pens->setGeometry(QRect(320, 440, 111, 51));
        Update_Pens->setFont(font3);
        Update_Pens->setFocusPolicy(Qt::NoFocus);
        End_Game_Button = new QPushButton(tab);
        End_Game_Button->setObjectName(QString::fromUtf8("End_Game_Button"));
        End_Game_Button->setGeometry(QRect(10, 440, 111, 51));
        End_Game_Button->setFont(font3);
        End_Game_Button->setFocusPolicy(Qt::NoFocus);
        Reset_All = new QPushButton(tab);
        Reset_All->setObjectName(QString::fromUtf8("Reset_All"));
        Reset_All->setGeometry(QRect(490, 580, 61, 41));
        Reset_All->setFont(font3);
        Reset_All->setFocusPolicy(Qt::NoFocus);
        show_score = new QCheckBox(tab);
        show_score->setObjectName(QString::fromUtf8("show_score"));
        show_score->setGeometry(QRect(40, 660, 92, 23));
        comboTheme = new QComboBox(tab);
        comboTheme->setObjectName(QString::fromUtf8("comboTheme"));
        comboTheme->setGeometry(QRect(428, 630, 121, 26));
        Remote->addTab(tab, QString());
        S = new QWidget();
        S->setObjectName(QString::fromUtf8("S"));
        verticalLayoutWidget_4 = new QWidget(S);
        verticalLayoutWidget_4->setObjectName(QString::fromUtf8("verticalLayoutWidget_4"));
        verticalLayoutWidget_4->setGeometry(QRect(0, 110, 161, 66));
        verticalLayout_4 = new QVBoxLayout(verticalLayoutWidget_4);
        verticalLayout_4->setSpacing(6);
        verticalLayout_4->setContentsMargins(11, 11, 11, 11);
        verticalLayout_4->setObjectName(QString::fromUtf8("verticalLayout_4"));
        verticalLayout_4->setContentsMargins(0, 0, 0, 0);
        Hotkey_Checkbox = new QCheckBox(verticalLayoutWidget_4);
        Hotkey_Checkbox->setObjectName(QString::fromUtf8("Hotkey_Checkbox"));

        verticalLayout_4->addWidget(Hotkey_Checkbox);

        Usehotkey_Help = new QPushButton(verticalLayoutWidget_4);
        Usehotkey_Help->setObjectName(QString::fromUtf8("Usehotkey_Help"));

        verticalLayout_4->addWidget(Usehotkey_Help);

        verticalLayoutWidget_5 = new QWidget(S);
        verticalLayoutWidget_5->setObjectName(QString::fromUtf8("verticalLayoutWidget_5"));
        verticalLayoutWidget_5->setGeometry(QRect(0, 0, 581, 61));
        verticalLayout_5 = new QVBoxLayout(verticalLayoutWidget_5);
        verticalLayout_5->setSpacing(6);
        verticalLayout_5->setContentsMargins(11, 11, 11, 11);
        verticalLayout_5->setObjectName(QString::fromUtf8("verticalLayout_5"));
        verticalLayout_5->setContentsMargins(0, 0, 0, 0);
        line_5 = new QFrame(verticalLayoutWidget_5);
        line_5->setObjectName(QString::fromUtf8("line_5"));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);

        verticalLayout_5->addWidget(line_5);

        Countdown_Checkbox = new QCheckBox(verticalLayoutWidget_5);
        Countdown_Checkbox->setObjectName(QString::fromUtf8("Countdown_Checkbox"));

        verticalLayout_5->addWidget(Countdown_Checkbox);

        Countdown_Detail = new QLabel(verticalLayoutWidget_5);
        Countdown_Detail->setObjectName(QString::fromUtf8("Countdown_Detail"));

        verticalLayout_5->addWidget(Countdown_Detail);

        verticalLayoutWidget_6 = new QWidget(S);
        verticalLayoutWidget_6->setObjectName(QString::fromUtf8("verticalLayoutWidget_6"));
        verticalLayoutWidget_6->setGeometry(QRect(0, 60, 151, 51));
        verticalLayout_6 = new QVBoxLayout(verticalLayoutWidget_6);
        verticalLayout_6->setSpacing(6);
        verticalLayout_6->setContentsMargins(11, 11, 11, 11);
        verticalLayout_6->setObjectName(QString::fromUtf8("verticalLayout_6"));
        verticalLayout_6->setContentsMargins(0, 0, 0, 0);
        Alway_on_top_Checkbox = new QCheckBox(verticalLayoutWidget_6);
        Alway_on_top_Checkbox->setObjectName(QString::fromUtf8("Alway_on_top_Checkbox"));

        verticalLayout_6->addWidget(Alway_on_top_Checkbox);

        line = new QFrame(S);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(150, 60, 16, 121));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(S);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(0, 100, 581, 21));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(S);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(0, 50, 581, 21));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_6 = new QFrame(S);
        line_6->setObjectName(QString::fromUtf8("line_6"));
        line_6->setGeometry(QRect(270, 110, 20, 71));
        line_6->setFrameShape(QFrame::VLine);
        line_6->setFrameShadow(QFrame::Sunken);
        line_7 = new QFrame(S);
        line_7->setObjectName(QString::fromUtf8("line_7"));
        line_7->setGeometry(QRect(400, 60, 16, 121));
        line_7->setFrameShape(QFrame::VLine);
        line_7->setFrameShadow(QFrame::Sunken);
        line_8 = new QFrame(S);
        line_8->setObjectName(QString::fromUtf8("line_8"));
        line_8->setGeometry(QRect(570, 0, 20, 181));
        line_8->setFrameShape(QFrame::VLine);
        line_8->setFrameShadow(QFrame::Sunken);
        line_9 = new QFrame(S);
        line_9->setObjectName(QString::fromUtf8("line_9"));
        line_9->setGeometry(QRect(0, 170, 581, 16));
        line_9->setFrameShape(QFrame::HLine);
        line_9->setFrameShadow(QFrame::Sunken);
        SpeedHelp_Button = new QPushButton(S);
        SpeedHelp_Button->setObjectName(QString::fromUtf8("SpeedHelp_Button"));
        SpeedHelp_Button->setGeometry(QRect(320, 70, 75, 31));
        TimerPreset_Checkbox = new QCheckBox(S);
        TimerPreset_Checkbox->setObjectName(QString::fromUtf8("TimerPreset_Checkbox"));
        TimerPreset_Checkbox->setGeometry(QRect(20, 190, 171, 17));
        TimerPreset_Checkbox->setChecked(false);
        checkBox = new QCheckBox(S);
        checkBox->setObjectName(QString::fromUtf8("checkBox"));
        checkBox->setGeometry(QRect(20, 270, 70, 17));
        line_10 = new QFrame(S);
        line_10->setObjectName(QString::fromUtf8("line_10"));
        line_10->setGeometry(QRect(0, 250, 581, 16));
        line_10->setFrameShape(QFrame::HLine);
        line_10->setFrameShadow(QFrame::Sunken);
        CurrentTime_Checkbox = new QCheckBox(S);
        CurrentTime_Checkbox->setObjectName(QString::fromUtf8("CurrentTime_Checkbox"));
        CurrentTime_Checkbox->setGeometry(QRect(288, 130, 121, 20));
        Stopwatch_Checkbox = new QCheckBox(S);
        Stopwatch_Checkbox->setObjectName(QString::fromUtf8("Stopwatch_Checkbox"));
        Stopwatch_Checkbox->setGeometry(QRect(170, 130, 111, 20));
        label_2 = new QLabel(S);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(20, 300, 451, 16));
        AwayName_Input = new QLineEdit(S);
        AwayName_Input->setObjectName(QString::fromUtf8("AwayName_Input"));
        AwayName_Input->setGeometry(QRect(20, 330, 571, 31));
        QFont font12;
        font12.setPointSize(14);
        AwayName_Input->setFont(font12);
        AwayName_Input->setMaxLength(30);
        HomeName_Input = new QLineEdit(S);
        HomeName_Input->setObjectName(QString::fromUtf8("HomeName_Input"));
        HomeName_Input->setGeometry(QRect(30, 370, 141, 31));
        HomeName_Input->setFont(font12);
        HomeName_Input->setMaxLength(30);
        StopMusic_Button = new QPushButton(S);
        StopMusic_Button->setObjectName(QString::fromUtf8("StopMusic_Button"));
        StopMusic_Button->setGeometry(QRect(50, 420, 121, 23));
        To_Checkbox = new QCheckBox(S);
        To_Checkbox->setObjectName(QString::fromUtf8("To_Checkbox"));
        To_Checkbox->setGeometry(QRect(10, 450, 101, 21));
        To_Checkbox->setFont(font5);
        Seconds_To_Input = new QSpinBox(S);
        Seconds_To_Input->setObjectName(QString::fromUtf8("Seconds_To_Input"));
        Seconds_To_Input->setGeometry(QRect(190, 450, 42, 22));
        Seconds_To_Input->setMaximum(59);
        Clock_Symble_Label_2 = new QLabel(S);
        Clock_Symble_Label_2->setObjectName(QString::fromUtf8("Clock_Symble_Label_2"));
        Clock_Symble_Label_2->setGeometry(QRect(170, 450, 20, 21));
        Clock_Symble_Label_2->setFont(font7);
        Minutes_To_In = new QSpinBox(S);
        Minutes_To_In->setObjectName(QString::fromUtf8("Minutes_To_In"));
        Minutes_To_In->setGeometry(QRect(120, 450, 42, 22));
        Remote->addTab(S, QString());
        Sound = new QWidget();
        Sound->setObjectName(QString::fromUtf8("Sound"));
        Sound->setEnabled(true);
        PlaySound_Checkbox = new QCheckBox(Sound);
        PlaySound_Checkbox->setObjectName(QString::fromUtf8("PlaySound_Checkbox"));
        PlaySound_Checkbox->setEnabled(true);
        PlaySound_Checkbox->setGeometry(QRect(10, 10, 121, 41));
        PlaySound_Checkbox->setFont(font12);
        BrowseFile_Input = new QLineEdit(Sound);
        BrowseFile_Input->setObjectName(QString::fromUtf8("BrowseFile_Input"));
        BrowseFile_Input->setEnabled(false);
        BrowseFile_Input->setGeometry(QRect(10, 60, 221, 21));
        Browsefile_Button = new QPushButton(Sound);
        Browsefile_Button->setObjectName(QString::fromUtf8("Browsefile_Button"));
        Browsefile_Button->setEnabled(false);
        Browsefile_Button->setGeometry(QRect(240, 61, 75, 21));
        horizontalSlider = new QSlider(Sound);
        horizontalSlider->setObjectName(QString::fromUtf8("horizontalSlider"));
        horizontalSlider->setEnabled(false);
        horizontalSlider->setGeometry(QRect(10, 120, 561, 31));
        horizontalSlider->setOrientation(Qt::Horizontal);
        label = new QLabel(Sound);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 100, 71, 16));
        label->setFont(font12);
        TestSound_Button = new QPushButton(Sound);
        TestSound_Button->setObjectName(QString::fromUtf8("TestSound_Button"));
        TestSound_Button->setEnabled(false);
        TestSound_Button->setGeometry(QRect(320, 60, 75, 23));
        Warning_Label = new QLabel(Sound);
        Warning_Label->setObjectName(QString::fromUtf8("Warning_Label"));
        Warning_Label->setGeometry(QRect(40, 220, 481, 71));
        QFont font13;
        font13.setFamily(QString::fromUtf8("Arial"));
        font13.setPointSize(36);
        Warning_Label->setFont(font13);
        Warning_Label->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        SoundSpeed_Slider = new QSlider(Sound);
        SoundSpeed_Slider->setObjectName(QString::fromUtf8("SoundSpeed_Slider"));
        SoundSpeed_Slider->setEnabled(false);
        SoundSpeed_Slider->setGeometry(QRect(10, 170, 561, 31));
        SoundSpeed_Slider->setMinimum(-10);
        SoundSpeed_Slider->setMaximum(10);
        SoundSpeed_Slider->setOrientation(Qt::Horizontal);
        thumb = new QLabel(Sound);
        thumb->setObjectName(QString::fromUtf8("thumb"));
        thumb->setGeometry(QRect(190, 200, 161, 121));
        Remote->addTab(Sound, QString());
        Remote1 = new QWidget();
        Remote1->setObjectName(QString::fromUtf8("Remote1"));
        Status = new QLabel(Remote1);
        Status->setObjectName(QString::fromUtf8("Status"));
        Status->setGeometry(QRect(0, 260, 581, 71));
        QFont font14;
        font14.setPointSize(18);
        Status->setFont(font14);
        Status->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        pushButton = new QPushButton(Remote1);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(20, 20, 181, 23));
        line_4 = new QFrame(Remote1);
        line_4->setObjectName(QString::fromUtf8("line_4"));
        line_4->setGeometry(QRect(0, 250, 581, 16));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        IP_Label = new QLabel(Remote1);
        IP_Label->setObjectName(QString::fromUtf8("IP_Label"));
        IP_Label->setGeometry(QRect(10, 210, 561, 16));
        IP_Label->setFont(font12);
        IP_Label_2 = new QLabel(Remote1);
        IP_Label_2->setObjectName(QString::fromUtf8("IP_Label_2"));
        IP_Label_2->setGeometry(QRect(10, 230, 561, 21));
        QFont font15;
        font15.setPointSize(12);
        IP_Label_2->setFont(font15);
        Remote->addTab(Remote1, QString());
        Testing = new QLabel(centralWidget);
        Testing->setObjectName(QString::fromUtf8("Testing"));
        Testing->setGeometry(QRect(0, 820, 541, 20));
        ScoreboardMain->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(ScoreboardMain);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 581, 23));
        menuAbout = new QMenu(menuBar);
        menuAbout->setObjectName(QString::fromUtf8("menuAbout"));
        menuContributers = new QMenu(menuBar);
        menuContributers->setObjectName(QString::fromUtf8("menuContributers"));
        menuDonate = new QMenu(menuBar);
        menuDonate->setObjectName(QString::fromUtf8("menuDonate"));
        QFont font16;
        font16.setFamily(QString::fromUtf8("Segoe UI Light"));
        font16.setPointSize(14);
        font16.setBold(true);
        font16.setWeight(75);
        menuDonate->setFont(font16);
        ScoreboardMain->setMenuBar(menuBar);

        menuBar->addAction(menuAbout->menuAction());
        menuBar->addAction(menuContributers->menuAction());
        menuBar->addAction(menuDonate->menuAction());
        menuAbout->addAction(About_ActionBar);
        menuAbout->addAction(Hotkey_ActionBar);
        menuAbout->addAction(ChangeLog_ActionBar);
        menuContributers->addAction(actionXxRocketshotxX);
        menuContributers->addAction(actionSickmind33);
        menuDonate->addAction(actionDonate);

        retranslateUi(ScoreboardMain);

        Remote->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(ScoreboardMain);
    } // setupUi

    void retranslateUi(QMainWindow *ScoreboardMain)
    {
        ScoreboardMain->setWindowTitle(QApplication::translate("ScoreboardMain", "Scoreboard Control Panel", nullptr));
        About_ActionBar->setText(QApplication::translate("ScoreboardMain", "&About", nullptr));
        Hotkey_ActionBar->setText(QApplication::translate("ScoreboardMain", "&Hotkey Help", nullptr));
        ChangeLog_ActionBar->setText(QApplication::translate("ScoreboardMain", "&Changelog", nullptr));
        actionXxRocketshotxX->setText(QApplication::translate("ScoreboardMain", "&XxRocketshotxX", nullptr));
        actionSickmind33->setText(QApplication::translate("ScoreboardMain", "&Sickmind33", nullptr));
        actionDonate->setText(QApplication::translate("ScoreboardMain", "&Donate", nullptr));
        AwayUp2_Button->setText(QApplication::translate("ScoreboardMain", "+2", nullptr));
        PeriodUP_Button->setText(QApplication::translate("ScoreboardMain", "+", nullptr));
        AwayScore_Label->setText(QApplication::translate("ScoreboardMain", "0", nullptr));
        Update_Team_Button->setText(QApplication::translate("ScoreboardMain", "Update Team", nullptr));
        AwayUP_Button->setText(QApplication::translate("ScoreboardMain", "+", nullptr));
        HomeUP_Button->setText(QApplication::translate("ScoreboardMain", "+", nullptr));
        HomeUP2_Button->setText(QApplication::translate("ScoreboardMain", "+2", nullptr));
        AwayDOWN_Button->setText(QApplication::translate("ScoreboardMain", "-", nullptr));
        PeriodDOWN_Button->setText(QApplication::translate("ScoreboardMain", "-", nullptr));
        Timeset_Label->setText(QApplication::translate("ScoreboardMain", "Time Set", nullptr));
        HomeScore_Label->setText(QApplication::translate("ScoreboardMain", "0", nullptr));
        Reset_Button->setText(QApplication::translate("ScoreboardMain", "Reset Timer", nullptr));
        Start_Button->setText(QApplication::translate("ScoreboardMain", "Start", nullptr));
#ifndef QT_NO_SHORTCUT
        Start_Button->setShortcut(QString());
#endif // QT_NO_SHORTCUT
        Period_Label->setText(QApplication::translate("ScoreboardMain", "1", nullptr));
        HomeDOWN_Button->setText(QApplication::translate("ScoreboardMain", "-", nullptr));
        Swap_Button->setText(QApplication::translate("ScoreboardMain", "Swap Teams", nullptr));
        Reset_Score_Button->setText(QApplication::translate("ScoreboardMain", "Reset Score", nullptr));
        Clock_Symble_Label->setText(QApplication::translate("ScoreboardMain", ":", nullptr));
        TwentyP_Radio->setText(QApplication::translate("ScoreboardMain", "&20:00", nullptr));
        TenP_Radio->setText(QApplication::translate("ScoreboardMain", "&12:00", nullptr));
        FiveP_Radio->setText(QApplication::translate("ScoreboardMain", "&5:00", nullptr));
        FifteenP_Radio->setText(QApplication::translate("ScoreboardMain", "15:&00", nullptr));
        Clock_Minute10->setText(QApplication::translate("ScoreboardMain", "0", nullptr));
        Clock_Minute1->setText(QApplication::translate("ScoreboardMain", "0", nullptr));
        Clock_Second10->setText(QApplication::translate("ScoreboardMain", "0", nullptr));
        Clock_Second1->setText(QApplication::translate("ScoreboardMain", "0", nullptr));
        Clock_Colon->setText(QApplication::translate("ScoreboardMain", ":", nullptr));
        Minute10up->setText(QApplication::translate("ScoreboardMain", "+", nullptr));
        Minute1up->setText(QApplication::translate("ScoreboardMain", "+", nullptr));
        Second10up->setText(QApplication::translate("ScoreboardMain", "+", nullptr));
        Second1up->setText(QApplication::translate("ScoreboardMain", "+", nullptr));
        Minute10down->setText(QApplication::translate("ScoreboardMain", "-", nullptr));
        Minute1down->setText(QApplication::translate("ScoreboardMain", "-", nullptr));
        Second10down->setText(QApplication::translate("ScoreboardMain", "-", nullptr));
        Second1down->setText(QApplication::translate("ScoreboardMain", "-", nullptr));
        MS10up->setText(QApplication::translate("ScoreboardMain", "+", nullptr));
        MS10down->setText(QApplication::translate("ScoreboardMain", "-", nullptr));
        Clock_Colon_2->setText(QApplication::translate("ScoreboardMain", ".", nullptr));
        Clock_MS10->setText(QApplication::translate("ScoreboardMain", "0", nullptr));
        Update_Timer->setText(QApplication::translate("ScoreboardMain", "Update Clock", nullptr));
        Intermission_Button->setText(QApplication::translate("ScoreboardMain", "Intermission", nullptr));
        home_label->setText(QApplication::translate("ScoreboardMain", "Home", nullptr));
        away_label->setText(QApplication::translate("ScoreboardMain", "Away", nullptr));
        home_player_label->setText(QApplication::translate("ScoreboardMain", "Player", nullptr));
        Clock_Symble_Label_3->setText(QApplication::translate("ScoreboardMain", ":", nullptr));
        Clock_Symble_Label_4->setText(QApplication::translate("ScoreboardMain", ":", nullptr));
        Clock_Symble_Label_5->setText(QApplication::translate("ScoreboardMain", ":", nullptr));
        Clock_Symble_Label_6->setText(QApplication::translate("ScoreboardMain", ":", nullptr));
        HP1->setText(QString());
        HP2->setText(QString());
        AP1->setText(QString());
        AP2->setText(QString());
        home_pen_label->setText(QApplication::translate("ScoreboardMain", "Home Penalties", nullptr));
        away_pen_label->setText(QApplication::translate("ScoreboardMain", "Away Penalties", nullptr));
        Update_Pens->setText(QApplication::translate("ScoreboardMain", "Update\n"
"Penalties", nullptr));
        End_Game_Button->setText(QApplication::translate("ScoreboardMain", "End Game", nullptr));
        Reset_All->setText(QApplication::translate("ScoreboardMain", "Reset\n"
"All", nullptr));
        show_score->setText(QApplication::translate("ScoreboardMain", "CheckBox", nullptr));
        Remote->setTabText(Remote->indexOf(tab), QApplication::translate("ScoreboardMain", "Scoreboard", nullptr));
        Hotkey_Checkbox->setText(QApplication::translate("ScoreboardMain", "Use Hotkey", nullptr));
        Usehotkey_Help->setText(QApplication::translate("ScoreboardMain", "Help", nullptr));
        Countdown_Checkbox->setText(QApplication::translate("ScoreboardMain", "Countdown Input Box", nullptr));
        Countdown_Detail->setText(QApplication::translate("ScoreboardMain", "Enables to input box to countdown to make it easy to change if the timer is off by seconds", nullptr));
        Alway_on_top_Checkbox->setText(QApplication::translate("ScoreboardMain", "Always on top", nullptr));
        SpeedHelp_Button->setText(QApplication::translate("ScoreboardMain", "Help", nullptr));
        TimerPreset_Checkbox->setText(QApplication::translate("ScoreboardMain", "Preset Timer Reset", nullptr));
        checkBox->setText(QApplication::translate("ScoreboardMain", "XML", nullptr));
        CurrentTime_Checkbox->setText(QApplication::translate("ScoreboardMain", "Current Time", nullptr));
        Stopwatch_Checkbox->setText(QApplication::translate("ScoreboardMain", "Stopwatch", nullptr));
        label_2->setText(QApplication::translate("ScoreboardMain", "Output to a XML File (If this is on, it will not output to the .txt files)", nullptr));
        AwayName_Input->setText(QApplication::translate("ScoreboardMain", "Away", nullptr));
        HomeName_Input->setText(QApplication::translate("ScoreboardMain", "Home", nullptr));
        StopMusic_Button->setText(QApplication::translate("ScoreboardMain", "Stop Sound", nullptr));
        To_Checkbox->setText(QApplication::translate("ScoreboardMain", "To(optional)", nullptr));
        Clock_Symble_Label_2->setText(QApplication::translate("ScoreboardMain", ":", nullptr));
        Remote->setTabText(Remote->indexOf(S), QApplication::translate("ScoreboardMain", "Setting", nullptr));
#ifndef QT_NO_ACCESSIBILITY
        Sound->setAccessibleName(QString());
#endif // QT_NO_ACCESSIBILITY
        PlaySound_Checkbox->setText(QApplication::translate("ScoreboardMain", "Play Sound", nullptr));
        Browsefile_Button->setText(QApplication::translate("ScoreboardMain", "Browse File", nullptr));
        label->setText(QApplication::translate("ScoreboardMain", "Volume:", nullptr));
        TestSound_Button->setText(QApplication::translate("ScoreboardMain", "Test Sound", nullptr));
        Warning_Label->setText(QApplication::translate("ScoreboardMain", "Please stop the sound", nullptr));
        thumb->setText(QString());
        Remote->setTabText(Remote->indexOf(Sound), QApplication::translate("ScoreboardMain", "Sound", nullptr));
        Status->setText(QApplication::translate("ScoreboardMain", "Status: Not Connected", nullptr));
        pushButton->setText(QApplication::translate("ScoreboardMain", "Enable", nullptr));
        IP_Label->setText(QApplication::translate("ScoreboardMain", "Default IP: 127.0.0.1/Localhost | Port: 1234", nullptr));
        IP_Label_2->setText(QApplication::translate("ScoreboardMain", "If you want to remote over network please portfoward or use Hamachi", nullptr));
        Remote->setTabText(Remote->indexOf(Remote1), QApplication::translate("ScoreboardMain", "Remote", nullptr));
        Testing->setText(QApplication::translate("ScoreboardMain", "Error Output:", nullptr));
        menuAbout->setTitle(QApplication::translate("ScoreboardMain", "He&lp", nullptr));
        menuContributers->setTitle(QApplication::translate("ScoreboardMain", "&Contributers", nullptr));
        menuDonate->setTitle(QApplication::translate("ScoreboardMain", "&Donate", nullptr));
    } // retranslateUi

};

namespace Ui {
    class ScoreboardMain: public Ui_ScoreboardMain {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SCOREBOARDMAIN_H
